name: Build document

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
        sudo apt install -y maven
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Render the documentation
      run: >
        python
        -X dev
        -X warn_default_encoding
        -m sphinx
        -M html ./doc ./build/sphinx
        -W
        --keep-going
